---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: fluentbit_ubuntu_instance_2004
    image: geerlingguy/docker-ubuntu2004-ansible
    privileged: true
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fluentbit_ubuntu_instance_1804
    image: geerlingguy/docker-ubuntu1804-ansible
    privileged: true
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fluentbit_centos7_instance
    image: geerlingguy/docker-centos7-ansible
    privileged: true
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fluentbit_rockylinux8_instance
    image: geerlingguy/docker-rockylinux8-ansible
    privileged: true
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fluentbit_centos8_instance
    image: geerlingguy/docker-centos8-ansible
    privileged: true
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fluentbit_amazonlinux2_instance
    image: geerlingguy/docker-amazonlinux2-ansible
    privileged: true
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
