---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: fluentbit_ubuntu_instance_2004
    image: geerlingguy/docker-ubuntu2004-ansible
    privileged: true
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fluentbit_centos7_instance
    image: geerlingguy/docker-centos7-ansible
    privileged: true
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
provisioner:
  name: ansible
verifier:
  name: testinfra
